//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSupply
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drinking_water_quality_indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drinking_water_quality_indicator()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        public int Indicator_number { get; set; }
        public string Indicators { get; set; }
        public string Units_measurement { get; set; }
        public string Regulations { get; set; }
        public string Indicator_harmfulness { get; set; }
        public int Hazard_class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
