//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSupply
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_execution
    {
        public int Place_execution_number { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public int Subscribers_TIN { get; set; }
    
        public virtual Subscriber Subscriber { get; set; }
    }
}
