//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Contract_number { get; set; }
        public System.DateTime Signature_date { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime Finish_Date { get; set; }
        public int Indicator_number { get; set; }
        public int Volume_number { get; set; }
        public int Code_Employee { get; set; }
        public int Subscribers_TIN { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Drinking_water_quality_indicator Drinking_water_quality_indicator { get; set; }
        public virtual Subscriber Subscriber { get; set; }
        public virtual Volume_of_drinking_water_consumption Volume_of_drinking_water_consumption { get; set; }
    }
}
